version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: realworld
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: